name: Minecast
authors: [drtshock, Shadowwolf97]
version: ${project.version}
main: io.minecast.plugin.Minecast
softdepend: [Mobarena]
commands:
  tweet:
    permission: minecast.tweet
  'yes':
    usage: /<command>
  'no':
    usage: /<command>